[project]
name = "chatbot_frontend"
version = "0.1"
dependencies = [
    "requests~=2.31.0",
    "pandas~=2.2.2",
    "matplotlib~=3.9.2",
    "streamlit==1.29.0",
    "tabulate==0.9.0"
]

[project.optional-dependencies]
dev = ["black", "flake8"]